# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b64e56e669b1c3fabb9478814de775e4776d3bd7875636ebc385e0b46df3d98d54b7579a9fe7d72e176377575faf59cc50b2207f186c005602bd07ed8f3832

test:
  secret_key_base: 55e7cee80bf5efd64d9276ad4aca3f45316eb57d0d8e2d75618e47e854e24bc6c3ca2bdb520b439a3cad057839fd989e6d5bf75d5fdd47cdcd15bb2033f0d72e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
